services:

  shardsvr1_1:
    container_name: shardsvr1_1
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20001:27017
    volumes:
      - shardsvr1_1:/data/db
    networks:
      - mongo-shard-net

  shardsvr1_2:
    container_name: shardsvr1_2
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20002:27017
    volumes:
      - shardsvr1_2:/data/db
    networks:
      - mongo-shard-net

  shardsvr1_3:
    container_name: shardsvr1_3
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20003:27017
    volumes:
      - shardsvr1_3:/data/db
    networks:
      - mongo-shard-net

volumes:
  shardsvr1_1:
  shardsvr1_2:
  shardsvr1_3:

networks:
  mongo-shard-net:
    external: true
