services:

  configsvr1:
    container_name: configsvr1
    image: mongo:latest
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 10001:27017
    volumes:
      - configsvr1:/data/db
    networks:
      - mongo-shard-net

  configsvr2:
    container_name: configsvr2
    image: mongo:latest
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 10002:27017
    volumes:
      - configsvr2:/data/db
    networks:
      - mongo-shard-net

  configsvr3:
    container_name: configsvr3
    image: mongo:latest
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 10003:27017
    volumes:
      - configsvr3:/data/db
    networks:
      - mongo-shard-net

volumes:
  configsvr1:
  configsvr2:
  configsvr3:

networks:
  mongo-shard-net:
    external: true
